
extern zend_class_entry *zeplara_interfaces_container_invalidabstractexception_ce;

ZEPHIR_INIT_CLASS(Zeplara_Interfaces_Container_InvalidAbstractException);

ZEPHIR_INIT_FUNCS(zeplara_interfaces_container_invalidabstractexception_method_entry) {
	PHP_ABSTRACT_ME(Zeplara_Interfaces_Container_InvalidAbstractException, getAbstract, NULL)
	PHP_FE_END
};
