
extern zend_class_entry *zeplara_contracts_file_parser_compiledvalue_ce;

ZEPHIR_INIT_CLASS(Zeplara_Contracts_File_Parser_CompiledValue);

ZEPHIR_INIT_FUNCS(zeplara_contracts_file_parser_compiledvalue_method_entry) {
	PHP_ABSTRACT_ME(Zeplara_Contracts_File_Parser_CompiledValue, getValue, NULL)
	PHP_ABSTRACT_ME(Zeplara_Contracts_File_Parser_CompiledValue, getRawValue, NULL)
	PHP_FE_END
};
